Messages:
  prefix: "&7[&bOreSheep&7]&r "
  egg_give: "&aYou gave %player% &6&l%amount%X %sheep% &aspawn egg"
  egg_get: "&aYou received &6&l%amount%X %sheep% &aspawn egg"
  config_reload: "&a&lConfig reloaded"
  sheep_not_found: "&cSheep not Found!"
  player_not_found: "&a&lNo player found with that name"
  player_only: "&cThis command is only for players!"
  invalid_usage: "&cIncorrect usage!"
Sheep:
  diamond_sheep:
    name: "&b&lDiamond Sheep"
    #Dye color list https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/DyeColor.html
    color: LIGHT_BLUE
    drop-on-shear: diamond
    drop-amount: 1-3
  coal_sheep:
    name: "&8&lCoal Sheep"
    color: black
    drop-on-shear: coal
    drop-amount: 1-3
  iron_sheep:
    name: "&f&lIron Sheep"
    color: white
    drop-on-shear: iron_ingot
    drop-amount: 1-3
  gold_sheep:
    name: "&6&lGold Sheep"
    color: yellow
    drop-on-shear: gold_ingot
    drop-amount: 1-3
  emerald_sheep:
    name: "&2&lEmerald Sheep"
    color: green
    drop-on-shear: emerald
    drop-amount: 1-3